In [1]:
import pandas as pd

In [2]:
all_edit_info_pd = pd.read_csv('only_5_cells_test/all_edit_info.tsv', sep='\t')

In [3]:
all_edit_info_pd = all_edit_info_pd[all_edit_info_pd['position'] == 3000527]

In [4]:
all_edit_info_pd.head()

,barcode_position,barcode,contig,position,ref,alt,read_id,strand,dist_from_end,base_quality,mapping_quality,barcode_position.1,coverage,source
16,GGGACCTTCGAGCCAC-1:3000527,GGGACCTTCGAGCCAC-1,9,3000527,T,C,A01535:287:H3JJHDSX7:1:1616:4463:31641,+,46,37,255,GGGACCTTCGAGCCAC-1:3000527,12.0,9_C-1
17,GGGACCTTCGAGCCAC-1:3000527,GGGACCTTCGAGCCAC-1,9,3000527,T,C,A01535:287:H3JJHDSX7:1:1333:1289:8015,+,48,37,255,GGGACCTTCGAGCCAC-1:3000527,12.0,9_C-1
18,GGGACCTTCGAGCCAC-1:3000527,GGGACCTTCGAGCCAC-1,9,3000527,T,C,A01535:287:H3JJHDSX7:2:1624:24044:8124,+,50,37,255,GGGACCTTCGAGCCAC-1:3000527,12.0,9_C-1
19,GGGACCTTCGAGCCAC-1:3000527,GGGACCTTCGAGCCAC-1,9,3000527,T,A,A01535:287:H3JJHDSX7:1:2250:27552:14199,+,40,37,255,GGGACCTTCGAGCCAC-1:3000527,12.0,9_C-1
20,GGGACCTTCGAGCCAC-1:3000527,GGGACCTTCGAGCCAC-1,9,3000527,T,C,A01535:287:H3JJHDSX7:1:1570:27326:7326,+,36,37,255,GGGACCTTCGAGCCAC-1:3000527,12.0,9_C-1

In [8]:
filtered_site_info = pd.read_csv('only_5_cells_test/final_filtered_site_info_annotated.tsv', sep='\t')

In [9]:
filtered_site_info[filtered_site_info.position == 3000527]

,site_id,barcode,contig,position,ref,alt,strand,count,coverage,conversion,feature_name,feature_strand,feature_type,feature_conversion
2,GGGACCTTCGAGCCAC-1_9_3000527_T_C_+,GGGACCTTCGAGCCAC-1,9,3000527,T,C,+,10,12.0,T>C,.,.,.,NaN
13,GCTCAAACAAGGTCTT-1_9_3000527_T_A_+,GCTCAAACAAGGTCTT-1,9,3000527,T,A,+,1,7.0,T>A,.,.,.,NaN
16,GCTCAAACAAGGTCTT-1_9_3000527_T_C_+,GCTCAAACAAGGTCTT-1,9,3000527,T,C,+,6,7.0,T>C,.,.,.,NaN
32,GATCCCTCAGTAACGG-1_9_3000527_T_C_+,GATCCCTCAGTAACGG-1,9,3000527,T,C,+,4,4.0,T>C,.,.,.,NaN
36,GGGACCTTCGAGCCAC-1_9_3000527_T_A_+,GGGACCTTCGAGCCAC-1,9,3000527,T,A,+,2,12.0,T>A,.,.,.,NaN
38,GTTCATTAGTCATTGC-1_9_3000527_T_C_+,GTTCATTAGTCATTGC-1,9,3000527,T,C,+,4,4.0,T>C,.,.,.,NaN
56,TACCTGCAGACTTGTC-1_9_3000527_T_C_+,TACCTGCAGACTTGTC-1,9,3000527,T,C,+,4,4.0,T>C,.,.,.,NaN